#!/bin/bash
cp {$(find . -name "3-islower.c"),\
$(find . -name "4-isalpha.c"),\
$(find . -name "6-abs.c"),\
$(find . -name "0-isupper.c"),\
$(find . -name "1-isdigit.c"),\
$(find . -name "2-strlen.c"),\
$(find . -name "3-puts.c"),\
$(find . -name "9-strcpy.c"),\
$(find . -name "100-atoi.c"),\
$(find . -name "0-strcat.c"),\
$(find . -name "1-strncat.c"),\
$(find . -name "2-strncpy.c"),\
$(find . -name "3-strcmp.c"),\
$(find . -name "0-memset.c"),\
$(find . -name "1-memcpy.c"),\
$(find . -name "2-strchr.c"),\
$(find . -name "3-strspn.c"),\
$(find . -name "4-strpbrk.c"),\
$(find . -name "5-strstr.c"),\
} ~/holbertonschool-low_level_programming/0x18-dynamic_libraries
